name: macOS VNC

on: 
  workflow_dispatch:

jobs:
  macos-desktop:
    runs-on: macos-latest
    steps:
      - name: Включение встроенного VNC (Screen Sharing)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -configure -access -on \
          -clientopts -setvnclegacy -vnclegacy yes \
          -clientopts -setvncpw -vncpw "123456" \
          -restart -agent -privs -all

      - name: Прямая установка Ngrok (без Homebrew)
        run: |
          curl -sSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin/

      - name: Авторизация и запуск туннеля Ngrok
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          ngrok config add-authtoken $NGROK_AUTHTOKEN
          ngrok tcp 5900 > /dev/null &
          
      - name: Адрес для подключения
        run: |
          sleep 5
          echo "=========================================="
          echo "АДРЕС ДЛЯ VNC КЛИЕНТА:"
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' | sed 's/tcp:\/\///'
          echo "ПАРОЛЬ: 123456"
          echo "=========================================="

      - name: Поддержание работы (6 часов)
        run: sleep 21600
